# Configuração de Build para Corne com nice!nano v2
# Este arquivo define quais firmwares serão compilados

include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right

