manifest:
  version: "0.13"
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: urob
      repo-path: zmk
      revision: main
      import: true
      path: app

  self:
    path: config

